# Generated by Django 5.1.4 on 2024-12-11 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(default=datetime.datetime(2024, 12, 11, 10, 7, 36, 494775, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
